<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Tuesday 11th of February 2014 10:12:58 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://vervelogicshowcase.com/matrimonial/hybridauth/", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => true
			),

			"AOL"  => array ( 
				"enabled" => true 
			),

			"Yahoo" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "AIzaSyBLwBh9TI7YybizK6Tuz9TFlLS7oej2cYg", "secret" => "ogidGpQy5NeOQ52WRRv54VSs" )  ,             "scope"           => "https://www.googleapis.com/auth/userinfo.profile ". // optional
                               "https://www.googleapis.com/auth/userinfo.email"   , // optional
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "1523278297898087", "secret" => "a9c9925fadeeaad499fc9b1ac84c26b6" )
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "3Kxv9oP04rXfiQY0H4Rsbw", "secret" => "V7jLWd6oPghgDTJE3A51VxHsabg3jDfyRV9c2CBk4w" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "75whb1nxfs4pf7", "secret" => "JSJIce3MelV5HKpp" ) 
			),

			"Foursquare" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
